// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goxsafjqjxnugynjxukt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdveHNhZmpxanhudWd5bmp4dWt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NTU1NTEsImV4cCI6MjA2MjQzMTU1MX0.tE6B29NRxPZj9iXWkyWiJrSyzb5Jy8ATG6aZHqLUFO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);